### ISSUE TITLE
mysql plugin error

### ISSUE THREAD

**Issue by diyon4** [pmacct/pmacct#210]
Hi,

I'm trying to start a pmacct server with mysql enabled. I can configure fine but during the make and make install I get this error:

mysql_plugin.c: In function 'MY_DB_Connect':
mysql_plugin.c:669:3: error: unknown type name 'my_bool'
   my_bool reconnect = TRUE;
   ^

I'm getting my instructions from here: https://mehul-m-prajapati.github.io/open%20source/Installing-PMacct/

Thanks .

**Comment by paololucente** [comment]
Hi @diyon4 , thanks for reporting this. Can you say which pmacct version ('nfacctd -V' will tell) and which MySQL version ('mysql -V' will tell) you are using? Paolo

**Comment by diyon4** [comment]
Hi Paolo,

Thanks for responding unfortunately due to this error pmacct doesn’t install:

nfacctd -V
-bash: nfacctd: command not found

pmacct
-bash: pmacct: command not found

MySQL is running ver 8.0.11:

mysql -V
mysql  Ver 8.0.11 for Linux on x86_64 (MySQL Community Server - GPL)

Thank you,

**Comment by diyon4** [comment]
Hi Paolo,

Thanks for responding unfortunately due to this error pmacct doesn’t install:  

nfacctd -V
-bash: nfacctd: command not found

pmacct
-bash: pmacct: command not found

MySQL is running ver 8.0.11:

mysql -V
mysql  Ver 8.0.11 for Linux on x86_64 (MySQL Community Server - GPL)

Thank you,
Dyon

**Comment by paololucente** [comment]
Hi Dyon, 

Indeed, if you can't compile, you can't see the version - apologies :-D

Thanks for confirming the MySQL version, that helps: building works with 5.6 ( >= 5.6.3 ) and 5.7; i never tried with MySQL 8.0 so it is possible some API changed there - i will investigate and get back to you. 

Paolo

**Comment by diyon4** [comment]
Hi Paolo,

I downgraded MySQL as you suggested and the install complete. Unfortunately now it wont populate the MySQL. I suspect it may be a configuration error on my end.
Would you mind taking a look?

Thank you,
Dyon
[pmacctd.conf.txt](https://github.com/pmacct/pmacct/files/2193212/pmacctd.conf.txt)
![pmacct](https://user-images.githubusercontent.com/41143488/42699484-c360a21c-8675-11e8-8cfc-3321a6570319.PNG)

**Comment by paololucente** [comment]
@diyon4 : with the latest fix, it now compiles against MySQL 8.0. Wrt your config: perhaps you have too little traffic on the interface and things keep buffered - try to comment out plugin_buffer_size and plugin_pipe_size; or the interface is wrong - try to see if tcpdump can see any traffic. If this does not help, please get in touch by email to troubleshoot further. Paolo

**Comment by zaxeqaz** [comment]
Hello Paolo

I'm having the same issue using mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper.

Thanks.

**Comment by paololucente** [comment]
Hi @zaxeqaz , can you include some output of the issue you are facing? Paolo

**Comment by zaxeqaz** [comment]
Hi Paolo,

Sorry about that, here is the error when I try to run make:
![image](https://user-images.githubusercontent.com/43657922/46503418-a08c8c00-c7df-11e8-8991-67eeec97347e.png)


Thanks.

**Comment by paololucente** [comment]
Hi @zaxeqaz , thank you. Wow :) Can you please edit src/pmacct.h and insert "#include <stdbool.h>" after "#include <unistd.h>" (t should be line 35). Then recompile. Does it work for you? If yes i will patch code in master branch asap. Paolo

**Comment by zaxeqaz** [comment]
Hi Paolo,

Thank you for the reply I was able to get the nfacctd to mysql working with ver 8.0.

Thank you.
