### ISSUE TITLE
Pull request 102 (Kafka dynamic partitioning), breaks build on Ubuntu 16.04, with default librdkafka*

### ISSUE THREAD

**Issue by gekaklam** [pmacct/pmacct#162]
On a Ubuntu 16.04, trying to build from source fails after merging #102 , when using --enable-kafka. The following commands were used, and the error is:

```
$ ./configure --enable-kafka --enable-jansson
$ make
[...]
kafka_common.c: In function 'p_kafka_set_dynamic_partitioner':
kafka_common.c:175:66: error: 'rd_kafka_msg_partitioner_consistent_random' undeclared (first use in this function)
   rd_kafka_topic_conf_set_partitioner_cb(kafka_host->topic_cfg, &rd_kafka_msg_partitioner_consistent_random);
```

This is because the latest version of librdkafka1 and librdkafka-dev, on the Ubuntu 16.04 repo is 0.8.6-1.1, and as shown [here](https://github.com/confluentinc/confluent-kafka-python/issues/10#issuecomment-227734635), we need librdkafka >=0.9.1, for this. 

The problem is solved by including the [Confluent repo](https://docs.confluent.io/current/installation.html#deb-packages-via-apt) and upgrading these two packages from there.

```
wget -qO - http://packages.confluent.io/deb/3.3/archive.key | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/3.3 stable main"
sudo apt-get update && sudo apt-get upgrade librdkafka-dev librdkafka1
make clean
/configure --enable-kafka --enable-jansson
make
```
Now everything works fine.

I don't know how much of an "Issue" this is, I just thought to mention it here, since it might be important for some people.

**Comment by paololucente** [comment]
Hi Georgios, what code are you running? Master code (and code in 1.7.0 branch) do require librdkafka 0.9.2 or later to be installed. Paolo

**Comment by paololucente** [comment]
Hi Georgios, please disregard my previous comment and see commit 0f5eb515daf5a4a2514954719c49d46c4c281fdc which now correctly enforces minimum requirement of librdkafka 0.9.2 when compiling with --enable-kafka. I'd be ready to close this issue then. Paolo

**Comment by gekaklam** [comment]
Dear Paolo,

Yes, I was building from master because I need the rfc3339 timestamps, which were not available on 1.6.2. I didn't know about the requirements because of the version change. You can close the issue, thanks for the help!
